version: 0.2
env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - git remote set-url origin https://github.com/vighes/vighes.git
      - printenv
      - echo $(git describe --abbrev=0 --tags)
      - scripts/codebuild-git-wrapper.sh "https://github.com/vighes/vighes.git" "main"
      - git log | head -100
            
