version: 0.2
env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - scripts/codebuild-git-wrapper.sh "git@github.com:vighes/vighes.git" "main"
      - git log | head -100
            
