version: 0.2
env:
    git-credential-helper: yes
phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands: 
	        - codebuild-git-wrapper.sh "git@github.com:vighes/vighes.git" "main" # These environment variables come from the CFN stack
            - git log | head -100
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
    post_build:
        commands:
            - echo "we are in the post build phase"
            
